# Generated by Django 5.2 on 2025-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
