# Generated by Django 5.2 on 2025-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.CharField(
                choices=[
                    ("profile1.png", "프로필1"),
                    ("profile2.png", "프로필2"),
                    ("profile3.png", "프로필3"),
                    ("profile4.png", "프로필4"),
                    ("profile5.png", "프로필5"),
                ],
                default="profile1.png",
                max_length=100,
            ),
        ),
    ]
