# Generated by Django 5.2 on 2025-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남자"), ("F", "여자")],
                max_length=1,
                null=True,
            ),
        ),
    ]
