# Generated by Django 5.2 on 2025-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportpost_supportreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportpost',
            name='category',
            field=models.CharField(choices=[('general', '일반 문의'), ('bug', '버그 제보'), ('feature', '기능 요청'), ('account', '계정 관련'), ('other', '기타')], default='general', max_length=20),
        ),
    ]
