# Generated by Django 5.2 on 2025-05-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_supportpost_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
