# Generated by Django 5.2 on 2025-05-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lovelist",
            name="is_liked",
            field=models.BooleanField(default=True),
        ),
    ]
