# Generated by Django 5.2 on 2025-05-20 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_tagsearchlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="lovelist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lovelist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
