# Generated by Django 5.2 on 2025-05-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_lovelist_created_at_lovelist_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lovelist",
            name="emotion_tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lovelist",
            name="genius_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lovelist",
            name="genre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lovelist",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lovelist",
            name="lyrics",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lovelist",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
