# Generated by Django 5.2 on 2025-05-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0010_alter_chartsong_release_date"),
        ("main", "0005_lovelist_emotion_tags_lovelist_genius_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lovelist",
            name="song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chartsongs.chartsong",
            ),
        ),
    ]
