# Generated by Django 5.2 on 2025-05-01 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="song",
            unique_together={("title", "artist")},
        ),
        migrations.AlterUniqueTogether(
            name="usersong",
            unique_together={("user", "title", "artist")},
        ),
    ]
