# Generated by Django 5.2 on 2025-05-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0002_alter_song_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="top2_emotions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersong",
            name="top3_emotions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
