# Generated by Django 5.2 on 2025-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0003_alter_song_top2_emotions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="top3_emotions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
