# Generated by Django 5.2 on 2025-05-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0004_song_top3_emotions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Song",
        ),
    ]
