# Generated by Django 5.2.1 on 2025-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullLyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("original", models.TextField()),
                ("ko", models.TextField(blank=True)),
                ("en", models.TextField(blank=True)),
                ("ja", models.TextField(blank=True)),
                ("zh", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("title", "artist")},
            },
        ),
    ]
