# Generated by Django 5.2.1 on 2025-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_search", "0002_fulllyrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritesong",
            name="video_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
