# Generated by Django 5.2 on 2025-05-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_search", "0003_favoritesong_video_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoriteSong",
        ),
    ]
