# Generated by Django 5.2 on 2025-05-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("normalized_genre", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("title", "artist", "normalized_genre")},
            },
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
