# Generated by Django 5.2 on 2025-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0002_chartsong_delete_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsong",
            name="lylics",
            field=models.TextField(blank=True, null=True),
        ),
    ]
