# Generated by Django 5.2 on 2025-05-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0003_chartsong_lylics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chartsong",
            old_name="lylics",
            new_name="lyrics",
        ),
    ]
