# Generated by Django 5.2 on 2025-05-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0004_rename_lylics_chartsong_lyrics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chartsong",
            old_name="lyrics",
            new_name="lylics",
        ),
    ]
