# Generated by Django 5.2 on 2025-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0005_rename_lyrics_chartsong_lylics"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsong",
            name="album_cover_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
