# Generated by Django 5.2 on 2025-05-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0006_chartsong_album_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsong",
            name="release_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
