# Generated by Django 5.2 on 2025-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0007_chartsong_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsong",
            name="genius_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
