# Generated by Django 5.2 on 2025-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0008_chartsong_genius_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartsong",
            name="emotion_tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chartsong",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
