# Generated by Django 5.2 on 2025-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsongs", "0009_chartsong_emotion_tags_chartsong_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartsong",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
