# Generated by Django 5.2 on 2025-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedLyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=255)),
                ("style", models.CharField(max_length=50)),
                ("lyrics", models.TextField()),
                ("language", models.CharField(default="none", max_length=20)),
                ("image_file", models.ImageField(upload_to="album_covers/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.FloatField()),
            ],
        ),
    ]
