# Generated by Django 5.2 on 2025-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lyricsgen", "0004_alter_generatedlyrics_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedlyrics",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
