# Generated by Django 5.2 on 2025-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lyricsgen", "0005_generatedlyrics_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedlyrics",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
