# Generated by Django 5.2 on 2025-05-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="thumbnails/"
            ),
        ),
    ]
