# Generated by Django 5.2 on 2025-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="thumbnails/default.png",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
    ]
