# Generated by Django 5.2 on 2025-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_postrecentview"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="lovelist_songs",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="main.lovelist"
            ),
        ),
    ]
