# Generated by Django 5.2 on 2025-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0009_post_lovelist_songs"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
